# Generated by Django 3.0.8 on 2022-01-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20)),
                ('receiver_name', models.CharField(max_length=255)),
                ('city', models.CharField(choices=[('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Chennai', 'Chennai'), ('Banglore', 'Banglore'), ('Kolkata', 'Kolkata')], max_length=10)),
                ('time_of_sending', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
